INSERT INTO acceso (IDACCESO,CONTRASENYA,USUARIO) VALUES (1,'sebas','sebas')
INSERT INTO usuario_info (ACCESO_IDACCESO,GUSTOS) VALUES (1,'Pop')
INSERT INTO genero (IDGENERO,NOMBRE) VALUES (1,'Pop')
INSERT INTO cancion (IDCANCION,NOMBRE,ARTISTA,GENERO_IDGENERO) VALUES (1,'La vida es bella','Shakira',1)
INSERT INTO USUARIO_HAS_CANCION (USUARIO_ACCESO_IDACCESO,CANCION_IDCANCION) VALUES (1,1)

INSERT INTO acceso (IDACCESO,CONTRASENYA,USUARIO) VALUES (2,'juan','juan')
INSERT INTO usuario_info (ACCESO_IDACCESO,GUSTOS) VALUES (2,'Rock')
INSERT INTO genero (IDGENERO,NOMBRE) VALUES (2,'Rock')
INSERT INTO cancion (IDCANCION,NOMBRE,ARTISTA,GENERO_IDGENERO) VALUES (2,'Ola k ase','su morenito',2)
INSERT INTO USUARIO_HAS_CANCION (USUARIO_ACCESO_IDACCESO,CANCION_IDCANCION) VALUES (2,2)

INSERT INTO acceso (IDACCESO,CONTRASENYA,USUARIO) VALUES (3,'pedro','pedro')
INSERT INTO usuario_info (ACCESO_IDACCESO,GUSTOS) VALUES (3,'Salsa')
INSERT INTO genero (IDGENERO,NOMBRE) VALUES (3,'Salsa')
INSERT INTO cancion (IDCANCION,NOMBRE,ARTISTA,GENERO_IDGENERO) VALUES (3,'Ola','morenito',2)
INSERT INTO USUARIO_HAS_CANCION (USUARIO_ACCESO_IDACCESO,CANCION_IDCANCION) VALUES (3,3)

INSERT INTO cancion (IDCANCION,NOMBRE,ARTISTA,GENERO_IDGENERO) VALUES (4,'a','a',2)



INSERT INTO USUARIO_HAS_CANCION (USUARIO_ACCESO_IDACCESO,CANCION_IDCANCION) VALUES (2,1)
