;             
CREATE USER IF NOT EXISTS "SA" SALT '656af59bcd8aebbc' HASH '984635bdeffd01f11f769d302d89374fffa0e6c3b3d4df2ea4363e395c58001b' ADMIN;         
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;   
CREATE MEMORY TABLE "PUBLIC"."ACCESO"(
    "IDACCESO" INTEGER NOT NULL,
    "CONTRASENYA" VARCHAR(45),
    "USUARIO" VARCHAR(45)
);       
ALTER TABLE "PUBLIC"."ACCESO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("IDACCESO"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCESO;  
CREATE MEMORY TABLE "PUBLIC"."CANCION"(
    "IDCANCION" INTEGER NOT NULL,
    "ARTISTA" VARCHAR(45),
    "NOMBRE" VARCHAR(45),
    "GENERO_IDGENERO" INTEGER
);          
ALTER TABLE "PUBLIC"."CANCION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("IDCANCION");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CANCION; 
CREATE MEMORY TABLE "PUBLIC"."GENERO"(
    "IDGENERO" INTEGER NOT NULL,
    "NOMBRE" VARCHAR(45)
);        
ALTER TABLE "PUBLIC"."GENERO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7D" PRIMARY KEY("IDGENERO");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GENERO;  
CREATE MEMORY TABLE "PUBLIC"."USUARIO_HAS_CANCION"(
    "USUARIO_ACCESO_IDACCESO" INTEGER NOT NULL,
    "CANCION_IDCANCION" INTEGER NOT NULL
);            
ALTER TABLE "PUBLIC"."USUARIO_HAS_CANCION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("USUARIO_ACCESO_IDACCESO", "CANCION_IDCANCION");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO_HAS_CANCION;     
CREATE MEMORY TABLE "PUBLIC"."USUARIO_INFO"(
    "ACCESO_IDACCESO" INTEGER NOT NULL,
    "GUSTOS" VARCHAR(45)
);           
ALTER TABLE "PUBLIC"."USUARIO_INFO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7DD" PRIMARY KEY("ACCESO_IDACCESO");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USUARIO_INFO;            
ALTER TABLE "PUBLIC"."USUARIO_HAS_CANCION" ADD CONSTRAINT "PUBLIC"."FKN8Q0BJCMB45A9WQ37QYE5GYXI" FOREIGN KEY("USUARIO_ACCESO_IDACCESO") REFERENCES "PUBLIC"."USUARIO_INFO"("ACCESO_IDACCESO") NOCHECK;        
ALTER TABLE "PUBLIC"."USUARIO_HAS_CANCION" ADD CONSTRAINT "PUBLIC"."FKSVPQ3MB3K9RCVT8QC7MB3RX9E" FOREIGN KEY("CANCION_IDCANCION") REFERENCES "PUBLIC"."CANCION"("IDCANCION") NOCHECK;         
ALTER TABLE "PUBLIC"."CANCION" ADD CONSTRAINT "PUBLIC"."FKRJEX1A73JML5X2H5U31PWNDPN" FOREIGN KEY("GENERO_IDGENERO") REFERENCES "PUBLIC"."GENERO"("IDGENERO") NOCHECK;         
ALTER TABLE "PUBLIC"."USUARIO_INFO" ADD CONSTRAINT "PUBLIC"."FKL59QPB853PCS937SHXQV2YV2U" FOREIGN KEY("ACCESO_IDACCESO") REFERENCES "PUBLIC"."ACCESO"("IDACCESO") NOCHECK;    
